spring:
  datasource:
    url: jdbc:mysql://localhost:3306/spring-plus
    username: root
    password: ljy3838658!
    driver-class-name: com.mysql.cj.jdbc.Driver

#  sql:
#    init:
#      mode: always
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    database-platform: org.hibernate.dialect.MySQLDialect
#logging:
#  level:
#    root: debug
jwt:
  secret:
    key: n+8tUKAvOgGMKamBOmCTFi8xXndbMdYLeug2HVl0lVQ=